version: '3.5'

services:
  cache:
    image: redis
    expose:
      - 6379
  frontend:
    image: example-frontend
    build: ./example-frontend/.
    ports:
      - 5000:5000
  backend:
    image: example-backend
    build: ./example-backend/.
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
