version: '3.5'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
  cache:
    image: redis
    expose:
      - 6379
  frontend:
    image: example-frontend
    build: ./example-frontend/.
    ports:
      - 3000:3000
  backend:
    image: example-backend
    build: ./example-backend/.
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8083:8080
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  database:
